const WIDGET_TYPE = {
  RESULTS: {
    NAME: 'RESULTS',
    DESCRIPTION: 'RESULTS FOR QUERY'
  },
  MAP: {
    NAME: 'MAP',
    DESCRIPTION: 'MAP FOR'
  },
  ERROR: {
    NAME: 'ERROR',
    DESCRIPTION: 'ERROR FOR'
  },
  PENDING: {
    NAME: 'PENDING',
    DESCRIPTION: 'PENDING FOR QUERY'
  },
  SHOW_PAPER: {
    NAME: 'SHOW_PAPER',
    DESCRIPTION: 'SHOW PAPER'
  },
};

export default WIDGET_TYPE;
